import { CategoryDetail } from '@/types/modal-detail';

export const categoryDetail: CategoryDetail = {
  categoryDetail1: [
    { id: 1, text: 'トップス' },
    { id: 2, text: 'ジャケット/アウター' },
    { id: 3, text: 'パンツ' },
    { id: 4, text: 'スカート' },
    { id: 5, text: 'ワンピース' },
    { id: 6, text: '靴' },
    { id: 7, text: 'ルームウェア/パジャマ' },
    { id: 8, text: '家電・スマホ・カメラ' },
    { id: 9, text: 'レッグウェア' },
    { id: 10, text: '帽子' },
    { id: 11, text: 'バッグ' },
    { id: 12, text: 'アクセサリー' },
    { id: 13, text: 'ヘアアクセサリー' },
    { id: 14, text: '小物' },
    { id: 15, text: '時計' },
  ],
  categoryDetail2: [
    { id: 1, text: 'トップス' },
    { id: 2, text: 'ジャケット/アウター' },
    { id: 3, text: 'パンツ' },
    { id: 4, text: '靴' },
    { id: 5, text: 'バッグ' },
    { id: 6, text: 'スーツ' },
    { id: 7, text: '帽子' },
    { id: 8, text: 'アクセサリー' },
    { id: 9, text: '小物' },
    { id: 10, text: '時計' },
    { id: 11, text: '水着' },
    { id: 12, text: 'レッグウェア' },
    { id: 13, text: 'アンダーウェア' },
    { id: 14, text: 'その他' },
  ],
  categoryDetail3: [
    { id: 1, text: 'ベビー服(女の子用)~95cm' },
    { id: 2, text: 'ベビー服(男の子用)~95cm' },
    { id: 3, text: 'ベビー服(男女兼用)~95cm' },
    { id: 4, text: 'キッズ服(男の子用)~100cm' },
    { id: 5, text: 'キッズ服(男の子用)~100cm' },
    { id: 6, text: 'キッズ服(男の子用)~100cm' },
    { id: 7, text: 'キッズ靴' },
    { id: 8, text: '子ども用ファッション小物' },
    { id: 9, text: 'おむつ/トイレ/バス' },
    { id: 10, text: '外出/移動用品' },
    { id: 11, text: '授乳/食事' },
    { id: 12, text: 'ベビー家具/寝具/室内用品' },
    { id: 13, text: 'おもちゃ' },
    { id: 14, text: '行事/記念品' },
  ],
  categoryDetail4: [
    { id: 1, text: 'キッチン/食器' },
    { id: 2, text: 'ベッド/マットレス' },
    { id: 3, text: 'ソファ/ソファベッド' },
    { id: 4, text: '椅子/チェア' },
    { id: 5, text: '机/テーブル' },
    { id: 6, text: '収納家具' },
    { id: 7, text: 'ラグ/カーペット/マット' },
    { id: 8, text: 'カーテン/ブラインド' },
    { id: 9, text: 'ライト照明' },
    { id: 10, text: '寝具' },
    { id: 11, text: 'インテリア小物' },
    { id: 12, text: '季節/年中行事' },
    { id: 13, text: 'その他' },
  ],
  categoryDetail5: [
    { id: 1, text: '本' },
    { id: 2, text: '漫画' },
    { id: 3, text: '雑誌' },
    { id: 4, text: 'CD' },
    { id: 5, text: 'DVD/ブルーレイ' },
    { id: 6, text: 'レコード' },
    { id: 7, text: 'テレビゲーム' },
  ],
  categoryDetail6: [
    { id: 1, text: 'おもちゃ' },
    { id: 2, text: 'タレントグッズ' },
    { id: 3, text: 'コミック/アニメグッズ' },
    { id: 4, text: 'トレーディングカード' },
    { id: 5, text: 'フィギュア' },
    { id: 6, text: '楽器/器材' },
    { id: 7, text: 'コレクション' },
    { id: 8, text: 'ミリタリー' },
    { id: 9, text: '美術品' },
    { id: 10, text: 'アート用品' },
    { id: 11, text: 'その他' },
  ],
  categoryDetail7: [
    { id: 1, text: 'ベースメイク' },
    { id: 2, text: 'メイクアップ' },
    { id: 3, text: 'ネイルケア' },
    { id: 4, text: '香水' },
    { id: 5, text: 'スキンケア/基礎化粧品' },
    { id: 6, text: 'ヘアケア' },
    { id: 7, text: 'ボディケア' },
    { id: 8, text: 'オーラルケア' },
    { id: 9, text: 'リラクセーション' },
    { id: 10, text: 'ダイエット' },
    { id: 11, text: 'その他' },
  ],
  categoryDetail8: [
    { id: 1, text: 'スマートフォン/携帯電話' },
    { id: 2, text: 'スマホアクセサリー' },
    { id: 3, text: 'PC/タブレット' },
    { id: 4, text: 'カメラ' },
    { id: 5, text: 'テレビ/映像機器' },
    { id: 6, text: 'オーディオ機器' },
    { id: 7, text: '美容/健康' },
    { id: 8, text: '冷暖房/空間' },
    { id: 9, text: '生活家電' },
    { id: 10, text: 'その他' },
  ],
  categoryDetail9: [
    { id: 1, text: 'ゴルフ' },
    { id: 2, text: 'フィッシング' },
    { id: 3, text: '自転車' },
    { id: 4, text: 'トレーニング/エクササイズ' },
    { id: 5, text: '野球' },
    { id: 6, text: 'サッカー/フットサル' },
    { id: 7, text: 'テニス' },
    { id: 8, text: 'スノーボード' },
    { id: 9, text: 'スキー' },
    { id: 10, text: 'その他スポーツ' },
    { id: 11, text: 'アウトドア' },
    { id: 12, text: 'その他' },
  ],
  categoryDetail10: [
    { id: 1, text: 'アクセサリー(女性用)' },
    { id: 2, text: 'ファッション/小物' },
    { id: 3, text: 'アクセサリー/時計' },
    { id: 4, text: '日用品/インテリア' },
    { id: 5, text: '趣味/おもちゃ' },
    { id: 6, text: 'キッズ/ベビー' },
    { id: 7, text: '素材/材料' },
    { id: 8, text: '二次創作物' },
    { id: 9, text: 'その他' },
  ],
  categoryDetail11: [
    { id: 1, text: '音楽' },
    { id: 2, text: 'スポーツ' },
    { id: 3, text: '演劇/芸能' },
    { id: 4, text: 'イベント' },
    { id: 5, text: '映画' },
    { id: 6, text: '施設利用券' },
    { id: 7, text: '優待券/割引券' },
    { id: 8, text: 'その他' },
  ],
  categoryDetail12: [
    { id: 1, text: '自転車本体' },
    { id: 2, text: '自転車タイヤ/ホイール' },
    { id: 3, text: '自動車パーツ' },
    { id: 4, text: '自動車アクセサリー' },
    { id: 5, text: 'オートバイ車体' },
    { id: 6, text: 'オートバイパーツ' },
    { id: 7, text: 'オートバイアクセサリー' },
  ],
  categoryDetail13: [
    { id: 1, text: 'まとめ売り' },
    { id: 2, text: 'ペット用品' },
    { id: 3, text: '食品' },
    { id: 4, text: '飲料/酒' },
    { id: 5, text: '日用品/生活雑貨/旅行' },
    { id: 6, text: 'アンティーク/コレクション' },
    { id: 7, text: '文房具/事務用品' },
    { id: 8, text: '事務/店舗用品' },
    { id: 9, text: 'その他' },
  ],
  categoryDetail14: [{ id: 1, text: '' }],
};
