import { CategoryDetail } from '@/types/header/modal-detail';

export const categoryDetail: CategoryDetail = {
  categoryDetail1: [
    { id: 15, text: 'トップス' },
    { id: 16, text: 'ジャケット/アウター' },
    { id: 17, text: 'パンツ' },
    { id: 18, text: 'スカート' },
    { id: 19, text: 'ワンピース' },
    { id: 20, text: '靴' },
    { id: 21, text: 'ルームウェア/パジャマ' },
    { id: 22, text: '家電・スマホ・カメラ' },
    { id: 23, text: 'レッグウェア' },
    { id: 24, text: '帽子' },
    { id: 25, text: 'バッグ' },
    { id: 26, text: 'アクセサリー' },
    { id: 27, text: 'ヘアアクセサリー' },
    { id: 28, text: '小物' },
    { id: 29, text: '時計' },
  ],
  categoryDetail2: [
    { id: 30, text: 'トップス' },
    { id: 31, text: 'ジャケット/アウター' },
    { id: 32, text: 'パンツ' },
    { id: 33, text: '靴' },
    { id: 34, text: 'バッグ' },
    { id: 35, text: 'スーツ' },
    { id: 36, text: '帽子' },
    { id: 37, text: 'アクセサリー' },
    { id: 38, text: '小物' },
    { id: 39, text: '時計' },
    { id: 40, text: '水着' },
    { id: 41, text: 'レッグウェア' },
    { id: 42, text: 'アンダーウェア' },
    { id: 43, text: 'その他' },
  ],
  categoryDetail3: [
    { id: 44, text: 'ベビー服(女の子用)~95cm' },
    { id: 45, text: 'ベビー服(男の子用)~95cm' },
    { id: 46, text: 'ベビー服(男女兼用)~95cm' },
    { id: 47, text: 'キッズ服(男の子用)~100cm' },
    { id: 48, text: 'キッズ服(男の子用)~100cm' },
    { id: 49, text: 'キッズ服(男の子用)~100cm' },
    { id: 50, text: 'キッズ靴' },
    { id: 51, text: '子ども用ファッション小物' },
    { id: 52, text: 'おむつ/トイレ/バス' },
    { id: 53, text: '外出/移動用品' },
    { id: 54, text: '授乳/食事' },
    { id: 55, text: 'ベビー家具/寝具/室内用品' },
    { id: 56, text: 'おもちゃ' },
    { id: 57, text: '行事/記念品' },
  ],
  categoryDetail4: [
    { id: 58, text: 'キッチン/食器' },
    { id: 59, text: 'ベッド/マットレス' },
    { id: 60, text: 'ソファ/ソファベッド' },
    { id: 61, text: '椅子/チェア' },
    { id: 62, text: '机/テーブル' },
    { id: 63, text: '収納家具' },
    { id: 64, text: 'ラグ/カーペット/マット' },
    { id: 65, text: 'カーテン/ブラインド' },
    { id: 66, text: 'ライト照明' },
    { id: 67, text: '寝具' },
    { id: 68, text: 'インテリア小物' },
    { id: 69, text: '季節/年中行事' },
    { id: 70, text: 'その他' },
  ],
  categoryDetail5: [
    { id: 71, text: '本' },
    { id: 72, text: '漫画' },
    { id: 73, text: '雑誌' },
    { id: 74, text: 'CD' },
    { id: 75, text: 'DVD/ブルーレイ' },
    { id: 76, text: 'レコード' },
    { id: 77, text: 'テレビゲーム' },
  ],
  categoryDetail6: [
    { id: 78, text: 'おもちゃ' },
    { id: 79, text: 'タレントグッズ' },
    { id: 80, text: 'コミック/アニメグッズ' },
    { id: 81, text: 'トレーディングカード' },
    { id: 82, text: 'フィギュア' },
    { id: 83, text: '楽器/器材' },
    { id: 84, text: 'コレクション' },
    { id: 85, text: 'ミリタリー' },
    { id: 86, text: '美術品' },
    { id: 87, text: 'アート用品' },
    { id: 88, text: 'その他' },
  ],
  categoryDetail7: [
    { id: 89, text: 'ベースメイク' },
    { id: 90, text: 'メイクアップ' },
    { id: 91, text: 'ネイルケア' },
    { id: 92, text: '香水' },
    { id: 93, text: 'スキンケア/基礎化粧品' },
    { id: 94, text: 'ヘアケア' },
    { id: 95, text: 'ボディケア' },
    { id: 96, text: 'オーラルケア' },
    { id: 97, text: 'リラクセーション' },
    { id: 98, text: 'ダイエット' },
    { id: 99, text: 'その他' },
  ],
  categoryDetail8: [
    { id: 100, text: 'スマートフォン/携帯電話' },
    { id: 102, text: 'スマホアクセサリー' },
    { id: 103, text: 'PC/タブレット' },
    { id: 104, text: 'カメラ' },
    { id: 105, text: 'テレビ/映像機器' },
    { id: 106, text: 'オーディオ機器' },
    { id: 107, text: '美容/健康' },
    { id: 108, text: '冷暖房/空間' },
    { id: 109, text: '生活家電' },
    { id: 110, text: 'その他' },
  ],
  categoryDetail9: [
    { id: 111, text: 'ゴルフ' },
    { id: 112, text: 'フィッシング' },
    { id: 113, text: '自転車' },
    { id: 114, text: 'トレーニング/エクササイズ' },
    { id: 115, text: '野球' },
    { id: 116, text: 'サッカー/フットサル' },
    { id: 117, text: 'テニス' },
    { id: 118, text: 'スノーボード' },
    { id: 119, text: 'スキー' },
    { id: 120, text: 'その他スポーツ' },
    { id: 121, text: 'アウトドア' },
    { id: 122, text: 'その他' },
  ],
  categoryDetail10: [
    { id: 123, text: 'アクセサリー(女性用)' },
    { id: 124, text: 'ファッション/小物' },
    { id: 125, text: 'アクセサリー/時計' },
    { id: 126, text: '日用品/インテリア' },
    { id: 127, text: '趣味/おもちゃ' },
    { id: 128, text: 'キッズ/ベビー' },
    { id: 129, text: '素材/材料' },
    { id: 130, text: '二次創作物' },
    { id: 131, text: 'その他' },
  ],
  categoryDetail11: [
    { id: 132, text: '音楽' },
    { id: 133, text: 'スポーツ' },
    { id: 134, text: '演劇/芸能' },
    { id: 135, text: 'イベント' },
    { id: 136, text: '映画' },
    { id: 137, text: '施設利用券' },
    { id: 138, text: '優待券/割引券' },
    { id: 139, text: 'その他' },
  ],
  categoryDetail12: [
    { id: 140, text: '自転車本体' },
    { id: 141, text: '自転車タイヤ/ホイール' },
    { id: 142, text: '自動車パーツ' },
    { id: 143, text: '自動車アクセサリー' },
    { id: 144, text: 'オートバイ車体' },
    { id: 145, text: 'オートバイパーツ' },
    { id: 146, text: 'オートバイアクセサリー' },
  ],
  categoryDetail13: [
    { id: 147, text: 'まとめ売り' },
    { id: 148, text: 'ペット用品' },
    { id: 149, text: '食品' },
    { id: 150, text: '飲料/酒' },
    { id: 151, text: '日用品/生活雑貨/旅行' },
    { id: 152, text: 'アンティーク/コレクション' },
    { id: 153, text: '文房具/事務用品' },
    { id: 154, text: '事務/店舗用品' },
    { id: 155, text: 'その他' },
  ],
};
